In [1]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
#import
import numpy as np
import nltk
import string
from nltk.tokenize import TweetTokenizer
from collections import Counter
import pandas as pd
import gensim.models
import pickle
import csv

### Load Datasets

In [3]:
pos = [line.rstrip('\n') for line in open('../../data/filtered_data/cleaned_train_pos.txt')]
neg = [line.rstrip('\n') for line in open('../../data/filtered_data/cleaned_train_neg.txt')]
test = [line.rstrip('\n') for line in open('../../data/filtered_data/filtered_test_data.txt')]

pos[:10], neg[:10], test[:10]

(['',
  '0 appli call guess should visit right tho',
  '0 awesom ee peopl hahaha',
  '0 caro would lie pft think jealous harri fake tweet cont',
  '0 happi anniversari 1 month mur jaya sayang oo long last c',
  '0 lettuc amaz mayb buy good tast salad dress help',
  '0 new follow wave hey yall',
  '0 new w follow err doe welcom tink world',
  '0 nigga real ass girl follow',
  '0 polish on toe n feet still not ugli'],
 ['',
  '0',
  '0 chill fuck week nd',
  '0 didnt answer phone',
  '0 friend tonight',
  '0 rft hope result come negat pray wanna stay healthi',
  '0 text fake dnt text call no',
  '0 veiw er on twit cam live geographi',
  '00 olymp favorit shoe releas',
  '000 melhor amiga world'],
 ['sea doo pro sea scooter sport portabl seadoo sea scooter save air stay longer water',
  'shuck well work week cant come cheer on oh put batteri calcul',
  'not stay away bug babi',
  'no maam lol perfect fine not contagi anymor lmao',
  'whenev fall asleep watch tv alway wake headach',
  'nee

In [13]:
test = [line.rstrip('\n') for line in open('../../data/filtered_data/filtered_test_data.txt')]

In [15]:
test = [tweet if tweet != '' else 'empty' for tweet in test]

In [4]:
pos = [tweet if tweet != '' else 'empty' for tweet in pos]
neg = [tweet if tweet != '' else 'empty' for tweet in neg]
test = [tweet if tweet != '' else 'empty' for tweet in test]

In [5]:
tknzr = TweetTokenizer()
pos_tokens = list([tknzr.tokenize(tweet) for tweet in pos])
neg_tokens = list([tknzr.tokenize(tweet) for tweet in neg])
test_tokens = list([tknzr.tokenize(tweet) for tweet in test])

In [231]:
# Using the full dataset
pos_full = [line.rstrip('\n') for line in open('../../data/filtered_data/cleaned_train_pos_full.txt')]
neg_full = [line.rstrip('\n') for line in open('../../data/filtered_data/cleaned_train_neg_full.txt')]

pos_full = [tweet if tweet != '' else 'empty' for tweet in pos_full]
neg_full = [tweet if tweet != '' else 'empty' for tweet in neg_full]

pos_full_tokens = list([tknzr.tokenize(tweet) for tweet in pos_full])
neg_full_tokens = list([tknzr.tokenize(tweet) for tweet in neg_full])

# Word Embeddings

### Genrate word2vec model

In [11]:
test_tokens

[['sea',
  'doo',
  'pro',
  'sea',
  'scooter',
  'sport',
  'portabl',
  'seadoo',
  'sea',
  'scooter',
  'save',
  'air',
  'stay',
  'longer',
  'water'],
 ['shuck',
  'well',
  'work',
  'week',
  'cant',
  'come',
  'cheer',
  'on',
  'oh',
  'put',
  'batteri',
  'calcul'],
 ['not', 'stay', 'away', 'bug', 'babi'],
 ['no', 'maam', 'lol', 'perfect', 'fine', 'not', 'contagi', 'anymor', 'lmao'],
 ['whenev', 'fall', 'asleep', 'watch', 'tv', 'alway', 'wake', 'headach'],
 ['need',
  'get',
  'rid',
  'thing',
  'scare',
  'lol',
  'dont',
  'need',
  'car',
  'either',
  'need',
  'driver',
  'ed'],
 ['whatev', 'terribl', 'mood'],
 ['yess', 'thank', 'jordan', 'love', 'gonna', 'call', 'later'],
 ['friend', 'text', 'check', 'on', 'last', 'night'],
 ['follow', 'back', 'pleas', 'ur', 'uniti', 'tour', 'come', 'europ', 'sweden'],
 ['watch', 'yall', 'dumb', 'ass', 'get', 'lock', 'today', 'happi', '420'],
 ['obsess',
  'phase',
  'kill',
  'best',
  'album',
  'ever',
  'love',
  'yew',
  'ro

In [8]:
model = gensim.models.Word2Vec(test_tokens, size=200, window=5, min_count=1, workers=4)

In [9]:
model.wv.similarity('sad', 'night')

0.9997705320634287

In [10]:
model.wv.vocab

{'sea': <gensim.models.keyedvectors.Vocab at 0x1d1b6105d30>,
 'doo': <gensim.models.keyedvectors.Vocab at 0x1d1b6105d68>,
 'pro': <gensim.models.keyedvectors.Vocab at 0x1d1b6105ef0>,
 'scooter': <gensim.models.keyedvectors.Vocab at 0x1d1b6105f28>,
 'sport': <gensim.models.keyedvectors.Vocab at 0x1d1b6105f60>,
 'portabl': <gensim.models.keyedvectors.Vocab at 0x1d1b6105f98>,
 'seadoo': <gensim.models.keyedvectors.Vocab at 0x1d1b6105fd0>,
 'save': <gensim.models.keyedvectors.Vocab at 0x1d1b5331048>,
 'air': <gensim.models.keyedvectors.Vocab at 0x1d1b5331080>,
 'stay': <gensim.models.keyedvectors.Vocab at 0x1d1b53310b8>,
 'longer': <gensim.models.keyedvectors.Vocab at 0x1d1b53310f0>,
 'water': <gensim.models.keyedvectors.Vocab at 0x1d1b5331128>,
 'shuck': <gensim.models.keyedvectors.Vocab at 0x1d1b5331160>,
 'well': <gensim.models.keyedvectors.Vocab at 0x1d1b5331198>,
 'work': <gensim.models.keyedvectors.Vocab at 0x1d1b53311d0>,
 'week': <gensim.models.keyedvectors.Vocab at 0x1d1b5331208>,

In [234]:
# Using the full dataset
model_full = gensim.models.Word2Vec(pos_full_tokens + neg_full_tokens + test_tokens, size=100, window=5, min_count=1, workers=4)

# Tweets to vectors

In [30]:
def tweet2vector(tweet, model):
    return sum([model[word] for word in tknzr.tokenize(tweet)])

In [31]:
pos_vec = np.asarray([tweet2vector(tweet, model) for tweet in pos])
neg_vec = np.asarray([tweet2vector(tweet, model) for tweet in neg])

# Concatenate both
X = np.vstack((pos_vec, neg_vec))

In [32]:
len(X)

178213

In [33]:
#labels
y = np.concatenate((np.ones(len(pos_vec)), -1*np.ones(len(neg_vec))))

In [40]:
# Testing set
test_vec = np.asarray([tweet2vector(tweet, model) for tweet in test])

In [236]:
# Using the full dataset
pos_full_vec = np.asarray([tweet2vector(tweet, model_full) for tweet in pos_full])
neg_full_vec = np.asarray([tweet2vector(tweet, model_full) for tweet in neg_full])

# Concatenate both
X_full = np.vstack((pos_full_vec, neg_full_vec))

y_full = np.concatenate((np.ones(len(pos_full_vec)), -1*np.ones(len(neg_full_vec))))

##### Store data in pickle files

In [174]:
#pickle.dump( X, open( "../../data/word2vec/X.p", "wb" ));
#pickle.dump( y, open( "../../data/word2vec/y.p", "wb" ));
#pickle.dump( model, open( "../../data/word2vec/model.p", "wb" ));
#pickle.dump( pos_vec, open( "../../data/word2vec/pos_vec.p", "wb" ));
#pickle.dump( neg_vec, open( "../../data/word2vec/neg_vec.p", "wb" ))
#pickle.dump( test_vec, open( "../../data/word2vec/test_vec.p", "wb" ))

In [244]:
pickle.dump( X_full, open( "../../data/word2vec/X_full.p", "wb" ));
pickle.dump( model_full, open( "../../data/word2vec/model_full.p", "wb" ));
pickle.dump( pos_full_vec, open( "../../data/word2vec/pos_full_vec.p", "wb" ));
pickle.dump( neg_full_vec, open( "../../data/word2vec/neg_full_vec.p", "wb" ))
pickle.dump( y_full, open( "../../data/word2vec/y_full.p", "wb" ));

##### Load pickled Data

# Learning

#### Random Forest

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [37]:
clf = RandomForestClassifier(max_depth=20, random_state=0)

In [38]:
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=20, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [42]:
clf.predict(test_vec)

array([-1., -1., -1., ..., -1.,  1.,  1.])

In [ ]:
def training_error():
    y_pred = clf.predict(X)
    return sum(np.abs(y_pred-y))/(2*len(y))

In [44]:
predictions = clf.predict(test_vec)
create_csv_submission(np.arange(len(predictions))+1, predictions, '../../data/submissions/prediction')

##### Naive Bayes

In [199]:
from sklearn.naive_bayes import GaussianNB

In [200]:
clf = GaussianNB()
clf.fit(X, y)

GaussianNB(priors=None)

In [203]:
y_pred = clf.predict(X)
sum(np.abs(y_pred-y))/(2*len(y))

0.39423049945851313

In [204]:
predictions = clf.predict(test_vec)

In [43]:
def create_csv_submission(ids, y_pred, name):
    """
    Creates an output file in csv format for submission to kaggle
    Arguments: ids (event ids associated with each prediction)
               y_pred (predicted class labels)
               name (string name of .csv output file to be created)
    """
    idx = pickle.load( open( "../../data/submissions/idx.p", "rb" ))+1
    name += str(idx)
    with open(name, 'w') as csvfile:
        fieldnames = ['Id', 'Prediction']
        writer = csv.DictWriter(csvfile, delimiter=",", fieldnames=fieldnames)
        writer.writeheader()
        for r1, r2 in zip(ids, y_pred):
            writer.writerow({'Id':int(r1),'Prediction':int(r2)})
    pickle.dump( idx, open( "../../data/submissions/idx.p", "wb" ))

In [222]:
create_csv_submission(np.arange(len(predictions))+1, predictions, '../../data/submissions/prediction')

In [224]:
idx = pickle.load( open( "../../data/submissions/idx.p", "rb" ))

#### Neural Net

In [240]:
from sklearn.neural_network import MLPClassifier

In [241]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [245]:
clf.fit(X_full, y_full)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [246]:
predictions = clf.predict(test_vec)
create_csv_submission(np.arange(len(predictions))+1, predictions, '../../data/submissions/prediction')

In [254]:
predictions

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [256]:
indices = np.random.randint(len(X_full), size=100000)
y_pred = clf.predict(X[indices])
sum(np.abs(y_pred-y_full))/(2*len(y))

IndexError: index 1939092 is out of bounds for axis 0 with size 178213

array([1899111,  140330, 1810838, ..., 2083567,  746339,  491426])

In [251]:
len(X_full)

2173332

##### SVM

In [45]:
from sklearn.svm import SVC
clf = SVC()

In [ ]:
clf.fit(X, y) 

In [ ]:
training_error()

In [ ]:
predictions = clf.predict(test_vec)
create_csv_submission(np.arange(len(predictions))+1, predictions, '../../data/submissions/prediction')